PRODUCTION = False

REGRESSION_DATASET = "hotel-regression-dataset.csv"
CLASSIFICATION_DATASET = "hotel-classification-dataset.csv"

TARGET_COLUMN = 'Reviewer_Score'

TAGS_COLUMN = 'Tags'
HOTEL_NAME_COLUMN = 'Hotel_Name'
ADDRESS_COLUMN = 'Hotel_Address'
DATE_COLUMN = 'Review_Date'

CURRENT_VERSION = 1

ENCODE_COLS = {
    'trip_type': {
        'label': True,
        'oneHot': False,
    },
    'trv_type': {
        'label': True,
        'oneHot': False,
    },
    'room_type': {
        'label': True,
        'oneHot': False,
    },
    'Hotel_Name': {
        'label': True,
        'oneHot': False,
    },
    'Reviewer_Nationality': {
        'label': True,
        'oneHot': False,
    },
    'Hotel_Country': {
        'label': True,
        'oneHot': False,
    },
    'Hotel_City': {
        'label': True,
        'oneHot': False,
    },
}

cities_dict = {
    'London':[ 'London'],
    'Manchester': ['Manchester'],
    'Birmingham': ['Birmingham'],
    'Liverpool': ['Liverpool'],
    'Leeds': ['Leeds'],
    'Glasgow': ['Glasgow'],
    'Edinburgh': ['Edinburgh'],
    'Bristol': ['Bristol'],
    'Newcastle upon Tyne': ['Newcastle upon Tyne'],
    'Sheffield': ['Sheffield'],
    'Nottingham':[ 'Nottingham'],
    'Belfast': ['Belfast'],
    'Southampton': ['Southampton'],
    'Brighton and Hove': ['Brighton and Hove'],
    'Cardiff': ['Cardiff'],
    'Paris': ['Paris'],
    'Marseille': ['Marseille'],
    'Lyon': ['Lyon'],
    'Toulouse': ['Toulouse'],
    'Nice': ['Nice'],
    'Nantes': ['Nantes'],
    'Strasbourg': ['Strasbourg'],
    'Montpellier': ['Montpellier'],
    'Bordeaux': ['Bordeaux'],
    'Lille': ['Lille'],
    'Rennes': ['Rennes'],
    'Reims': ['Reims'],
    'Le Havre': ['Le Havre'],
    'Saint-Étienne': ['Saint-Étienne'],
    'Toulon': ['Toulon'],
    'Grenoble': ['Grenoble'],
    'Dijon': ['Dijon'],
    'Angers':[ 'Angers'],
    'Nîmes': ['Nîmes'],
    'Villeurbanne': ['Villeurbanne'],
    'Rome': ['Rome'],
    'Milan': ['Milan'],
    'Naples': ['Naples'],
    'Turin': ['Turin'],
    'Palermo':[ 'Palermo'],
    'Genoa': ['Genoa'],
    'Bologna': ['Bologna'],
    'Florence': ['Florence'],
    'Bari': ['Bari'],
    'Catania': ['Catania'],
    'Venice': ['Venice'],
    'Verona': ['Verona'],
    'Messina':[ 'Messina'],
    'Padua': ['Padua'],
    'Trieste':[ 'Trieste'],
    'Taranto':[ 'Taranto'],
    'Brescia':[ 'Brescia'],
    'Prato': ['Prato'],
    'Reggio Calabria': ['Reggio Calabria'],
    'Modena': ['Modena'],
    'Madrid': ['Madrid'],
    'Barcelona': ['Barcelona'],
    'Valencia': ['Valencia'],
    'Seville': ['Seville'],
    'Malaga': ['Malaga'],
    'Bilbao': ['Bilbao'],
    'Murcia': ['Murcia'],
    'Palma de Mallorca': ['Palma de Mallorca'],
    'Las Palmas': ['Las Palmas'],
    'Zaragoza': ['Zaragoza'],
    'Alicante': ['Alicante'],
    'Cordoba': ['Cordoba'],
    'Valladolid': ['Valladolid'],
    'Vigo': ['Vigo'],
    'Gijon': ['Gijon'],
    'L Hospitalet de Llobregat': ['L Hospitalet de Llobregat'],
    'La Coruna': ['La Coruna'],
    'Granada': ['Granada'],
    'Cartagena': ['Cartagena'],
    'San Sebastian':[ 'San Sebastian'],
    'Amsterdam': ['Amsterdam'],
    'Rotterdam': ['Rotterdam'],
    'The Hague': ['The Hague'],
    'Den Haag': ['Den Haag'],
    'Utrecht': ['Utrecht'],
    'Eindhoven': ['Eindhoven'],
    'Tilburg': ['Tilburg'],
    'Groningen': ['Groningen'],
    'Almere': ['Almere'],
    'Breda': ['Breda'],
    'Nijmegen': ['Nijmegen'],
    'Apeldoorn':[ 'Apeldoorn'],
    'Haarlem': ['Haarlem'],
    'Enschede':[ 'Enschede'],
    'Arnhem': ['Arnhem'],
    'Amersfoort': ['Amersfoort'],
    'Vienna': ['Vienna'],
    'Graz': ['Graz'],
    'Linz': ['Linz'],
    'Salzburg': ['Salzburg'],
    'Innsbruck': ['Innsbruck'],
    'Klagenfurt': ['Klagenfurt'],
    'Villach': ['Villach'],
    'Wels': ['Wels'],
    'Sankt Pölten': ['Sankt Pölten'],
    'Dornbirn': ['Dornbirn'],
    'Wiener Neustadt': ['Wiener Neustadt'],
    'Steyr': ['Steyr'],
    'Feldkirch': ['Feldkirch'],
    'Bregenz':['Bregenz'],
    'Leoben': ['Leoben']
}

